
package edu.columbia.cs.psl.scrape.wow;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ScrapeMasterService", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", wsdlLocation = "http://barclay.cs.columbia.edu:8282/ScrapeMasterService/ScrapeMaster?wsdl")
public class ScrapeMasterService
    extends Service
{

    private final static URL SCRAPEMASTERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.columbia.cs.psl.scrape.wow.ScrapeMasterService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.columbia.cs.psl.scrape.wow.ScrapeMasterService.class.getResource(".");
            url = new URL(baseUrl, "http://barclay.cs.columbia.edu:8282/ScrapeMasterService/ScrapeMaster?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://barclay.cs.columbia.edu:8282/ScrapeMasterService/ScrapeMaster?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SCRAPEMASTERSERVICE_WSDL_LOCATION = url;
    }

    public ScrapeMasterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScrapeMasterService() {
        super(SCRAPEMASTERSERVICE_WSDL_LOCATION, new QName("http://wow.scrape.psl.cs.columbia.edu/", "ScrapeMasterService"));
    }

    /**
     * 
     * @return
     *     returns ScrapeMaster
     */
    @WebEndpoint(name = "ScrapeMasterPort")
    public ScrapeMaster getScrapeMasterPort() {
        return super.getPort(new QName("http://wow.scrape.psl.cs.columbia.edu/", "ScrapeMasterPort"), ScrapeMaster.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScrapeMaster
     */
    @WebEndpoint(name = "ScrapeMasterPort")
    public ScrapeMaster getScrapeMasterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wow.scrape.psl.cs.columbia.edu/", "ScrapeMasterPort"), ScrapeMaster.class, features);
    }

}
