
package edu.columbia.cs.psl.scrape.wow;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ScrapeMaster", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScrapeMaster {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.RegisterResponse")
    public int register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.columbia.cs.psl.scrape.wow.Guild
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGuildToScrape", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetGuildToScrape")
    @ResponseWrapper(localName = "getGuildToScrapeResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetGuildToScrapeResponse")
    public Guild getGuildToScrape(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.columbia.cs.psl.scrape.wow.Toon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getToonToScrape", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetToonToScrape")
    @ResponseWrapper(localName = "getToonToScrapeResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetToonToScrapeResponse")
    public Toon getToonToScrape(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateGuildStatus", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.UpdateGuildStatus")
    @ResponseWrapper(localName = "updateGuildStatusResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.UpdateGuildStatusResponse")
    public void updateGuildStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateToonStatus", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.UpdateToonStatus")
    @ResponseWrapper(localName = "updateToonStatusResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.UpdateToonStatusResponse")
    public void updateToonStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateSlaveCount", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.UpdateSlaveCount")
    @ResponseWrapper(localName = "updateSlaveCountResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.UpdateSlaveCountResponse")
    public void updateSlaveCount(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getToonName", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetToonName")
    @ResponseWrapper(localName = "getToonNameResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetToonNameResponse")
    public String getToonName(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "processToon", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.ProcessToon")
    @ResponseWrapper(localName = "processToonResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.ProcessToonResponse")
    public void processToon(
        @WebParam(name = "arg0", targetNamespace = "")
        Toon arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "processGuild", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.ProcessGuild")
    @ResponseWrapper(localName = "processGuildResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.ProcessGuildResponse")
    public void processGuild(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Toon> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyIP", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetMyIP")
    @ResponseWrapper(localName = "getMyIPResponse", targetNamespace = "http://wow.scrape.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.scrape.wow.GetMyIPResponse")
    public long getMyIP();

}
